### ISSUE TITLE
plugin:elasticsearch@6.2.1	 Unable to connect to Elasticsearch at http://localhost:9200.

### ISSUE THREAD

**Issue by yanncarlier** [nitzantomer/ether-to-elasticsearch#18]
node_1                  | connecting to elasticsearch at: elasticsearch-kibana:9200
node_1                  | (node:1) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
node_1                  |     at Object.InvalidResponse (/home/node/app/node_modules/web3-core-helpers/src/errors.js:42:16)
node_1                  |     at XMLHttpRequest.request.onreadystatechange (/home/node/app/node_modules/web3-providers-http/src/index.js:60:32)
node_1                  |     at XMLHttpRequestEventTarget.dispatchEvent (/home/node/app/node_modules/xhr2/lib/xhr2.js:64:18)
node_1                  |     at XMLHttpRequest._setReadyState (/home/node/app/node_modules/xhr2/lib/xhr2.js:354:12)
node_1                  |     at XMLHttpRequest._onHttpRequestError (/home/node/app/node_modules/xhr2/lib/xhr2.js:544:12)
node_1                  |     at ClientRequest.<anonymous> (/home/node/app/node_modules/xhr2/lib/xhr2.js:414:24)
node_1                  |     at ClientRequest.emit (events.js:180:13)
node_1                  |     at Socket.socketErrorListener (_http_client.js:394:9)
node_1                  |     at Socket.emit (events.js:180:13)
node_1                  |     at emitErrorNT (internal/streams/destroy.js:64:8)
node_1                  |     at process._tickCallback (internal/process/next_tick.js:114:19)
node_1                  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
node_1                  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
node_1                  | connecting to elasticsearch at: elasticsearch-kibana:9200
node_1                  | (node:1) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
node_1                  |     at Object.InvalidResponse (/home/node/app/node_modules/web3-core-helpers/src/errors.js:42:16)
node_1                  |     at XMLHttpRequest.request.onreadystatechange (/home/node/app/node_modules/web3-providers-http/src/index.js:60:32)
node_1                  |     at XMLHttpRequestEventTarget.dispatchEvent (/home/node/app/node_modules/xhr2/lib/xhr2.js:64:18)
node_1                  |     at XMLHttpRequest._setReadyState (/home/node/app/node_modules/xhr2/lib/xhr2.js:354:12)
node_1                  |     at XMLHttpRequest._onHttpRequestError (/home/node/app/node_modules/xhr2/lib/xhr2.js:544:12)
node_1                  |     at ClientRequest.<anonymous> (/home/node/app/node_modules/xhr2/lib/xhr2.js:414:24)
node_1                  |     at ClientRequest.emit (events.js:180:13)
node_1                  |     at Socket.socketErrorListener (_http_client.js:394:9)
node_1                  |     at Socket.emit (events.js:180:13)
node_1                  |     at emitErrorNT (internal/streams/destroy.js:64:8)
node_1                  |     at process._tickCallback (internal/process/next_tick.js:114:19)
node_1                  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
node_1                  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
node_1                  | connecting to elasticsearch at: elasticsearch-kibana:9200
node_1                  | (node:1) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
node_1                  |     at Object.InvalidResponse (/home/node/app/node_modules/web3-core-helpers/src/errors.js:42:16)
node_1                  |     at XMLHttpRequest.request.onreadystatechange (/home/node/app/node_modules/web3-providers-http/src/index.js:60:32)
node_1                  |     at XMLHttpRequestEventTarget.dispatchEvent (/home/node/app/node_modules/xhr2/lib/xhr2.js:64:18)
node_1                  |     at XMLHttpRequest._setReadyState (/home/node/app/node_modules/xhr2/lib/xhr2.js:354:12)
node_1                  |     at XMLHttpRequest._onHttpRequestError (/home/node/app/node_modules/xhr2/lib/xhr2.js:544:12)
node_1                  |     at ClientRequest.<anonymous> (/home/node/app/node_modules/xhr2/lib/xhr2.js:414:24)
node_1                  |     at ClientRequest.emit (events.js:180:13)
node_1                  |     at Socket.socketErrorListener (_http_client.js:394:9)
node_1                  |     at Socket.emit (events.js:180:13)
node_1                  |     at emitErrorNT (internal/streams/destroy.js:64:8)
node_1                  |     at process._tickCallback (internal/process/next_tick.js:114:19)
node_1                  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
node_1                  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ethertoelasticsearch_node_1 exited with code 0

**Comment by raullenchai** [comment]
"export PARITY=localhost:8545" should fix it.
