### ISSUE TITLE
Error: /home/node/app/node_modules/scrypt/build/Release/scrypt.node: invalid ELF

### ISSUE THREAD

**Issue by vjuge** [nitzantomer/ether-to-elasticsearch#19]
hello,

thanks for this project, but unfortunately not possible to test it.
First launch today
cloned the repo
launched npm install, npm run build
launched docker-compose up

and got the following error : 

Creating ethertoelasticsearch_elasticsearch-kibana_1 ...
Creating ethertoelasticsearch_node_1                 ... done
Attaching to ethertoelasticsearch_elasticsearch-kibana_1, ethertoelasticsearch_node_1
node_1                  | module.js:678
node_1                  |   return process.dlopen(module, path.toNamespacedPath(filename));
node_1                  |                  ^
node_1                  |
node_1                  | Error: /home/node/app/node_modules/scrypt/build/Release/scrypt.node: invalid ELF header
node_1                  |     at Object.Module._extensions..node (module.js:678:18)
node_1                  |     at Module.load (module.js:561:32)
node_1                  |     at tryModuleLoad (module.js:501:12)
node_1                  |     at Function.Module._load (module.js:493:3)
node_1                  |     at Module.require (module.js:593:17)
node_1                  |     at require (internal/module.js:11:18)
node_1                  |     at Object.<anonymous> (/home/node/app/node_modules/scrypt/index.js:3:20)
node_1                  |     at Module._compile (module.js:649:30)
node_1                  |     at Object.Module._extensions..js (module.js:660:10)
node_1                  |     at Module.load (module.js:561:32)
node_1                  |     at tryModuleLoad (module.js:501:12)
node_1                  |     at Function.Module._load (module.js:493:3)
node_1                  |     at Module.require (module.js:593:17)
node_1                  |     at require (internal/module.js:11:18)
node_1                  |     at Object.<anonymous> (/home/node/app/node_modules/scrypt.js/node.js:1:76)
node_1                  |     at Module._compile (module.js:649:30)
node_1                  |     at Object.Module._extensions..js (module.js:660:10)
node_1                  |     at Module.load (module.js:561:32)
node_1                  |     at tryModuleLoad (module.js:501:12)
node_1                  |     at Function.Module._load (module.js:493:3)
node_1                  |     at Module.require (module.js:593:17)
node_1                  |     at require (internal/module.js:11:18)
ethertoelasticsearch_node_1 exited with code 1

**Comment by ffox77** [comment]
This fixed the issue for me: https://github.com/barrysteyn/node-scrypt/issues/160#issuecomment-383753421
